### PR TITLE
Issue 18

### PR DESCRIPTION
**Pull request by mtholder**

### CODE REVIEW

**Comment by mtholder** [comment]
fixes https://github.com/OpenTreeOfLife/otcetera/issues/18

**Comment by josephwb** [comment]
Will my tests work now? Or is there different output?

**Comment by mtholder** [comment]
what tests?

**Comment by josephwb** [comment]
The counting of nodes that are supported by just trees, just taxonomy, and both.

**Comment by mtholder** [comment]
The output has changed but it is now more explicit. You'll now see something like:

    501 internal nodes where flagged as being supported in some sense.
        This means each of these nodes was:
        supported by at least one non-taxonomic input tree  or the internal node has a name.
    The breakdown of the types of supported nodes:
        294 unnamed internal nodes supported by an input tree internal node.
        0 unnamed internal nodes supported by an input tree expanded tip node.
        0 unnamed  internal nodes supported by an input tree internal node and another tree's expanded  tip node.
        5 named internal nodes had no support (other than the name).
        1 named internal nodes supported by an input tree internal node.
        122 named internal nodes supported by an input tree expanded tip node.
        0 named internal nodes supported by an input tree internal node and another tree's expanded  tip node.
    The following counts refer to redundant internal nodes (out-degree = 1). These are considered supported if their child is supported.
        0 unnamed redundant internal nodes supported by an input tree internal node.
        0 unnamed redundant  internal nodes supported by an input tree expanded tip node.
        0 unnamed  redundant  internal nodes supported by an input tree internal node and another tree's expanded  tip node.
        66  redundant named internal nodes had no support (other than the name).
        0  redundant named internal nodes supported by an input tree internal node.
        13  redundant named internal nodes supported by an input tree expanded tip node.
        0  redundant named internal nodes supported by an input tree internal node and another tree's expanded  tip node.
    0 unsupported nodes had out-degree > 1
    0 unsupported nodes had out-degree == 1 and were along a terminal path.
    0 unsupported nodes had out-degree == 1 and were along an internal path.
    501 total internal nodes checked.

Let me know if any of those stats need more explanation.

**Comment by josephwb** [comment]
Ah! I was tailing the logs, so only got part of the results.

This should work. Thanks Mark!

**Pull request merged**
