### PR TITLE
Delete subproblems on make clean

### PR DESCRIPTION
**Pull request by josephwb**
Minor edit to `Makefile.synth-v3` to delete subproblems when doing `Make -f Makefile.synth-v3 clean`.

### CODE REVIEW

**Comment by mtholder** [comment]
I don't think there are any bugs in this... but, I **really** don't like putting `rm -rf $(SOME_COMPUTED_VALUE)` in my Makefiles.

One typo in how `ARTIFACTS` is created, and there goes your home dir (and your day).

I'd prefer to either:
  1. suffer the downsides of a clean target that does not clean everthing, OR
  2. refactor this to removing files and using rmdir

**Comment by josephwb** [comment]
Agreed. Will update.

**Comment by josephwb** [comment]
I think the Makefile is now acceptable

**Comment by jimallman** [comment]
Travis errors include `/usr/include/x86_64-linux-gnu/bits/math-finite.h:177:1: error: unknown type name
     '__extern_always_inline'`

This macro seems to cause trouble in many projects (based on a quick googlin’), for example: https://github.com/pbenner/tfbayes#known-errors

It seems the common advice is to add it to compile options, eg ` -D__extern_always_inline=inline`

**Comment by josephwb** [comment]
Should I can this one @mtholder? I'm sure you have other/better ways to deal with this sort of thing.

**Comment by mtholder** [comment]
not sure if I'll find better ways, but this stuff is moving to the another repo, so I'll go ahead an close this one.

**Pull request closed without merging**
